name: ci-publish_nplug_proxy

on:
  workflow_dispatch:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build
      shell: bash
      run: |
        dotnet build -c Release ./src/NPlug.Proxy/NPlug.Proxy.csproj

    - name: Package
      shell: bash
      run: |
        dotnet pack -c Release ./src/NPlug.Proxy/NPlug.Proxy.csproj -p:IsPackable=true

    - name: Publish
      shell: bash
      run: |
        dotnet nuget push ./src/NPlug.Proxy/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
